### ISSUE TITLE
uvm_agent has no attribute 'is_active' during build_phase

### ISSUE THREAD

**Issue by tj-scherer** [pyuvm/pyuvm#147]
I am trying to create an agent using the following code:

```py
class Environment(uvm_env):
    def build_phase(self):
        self.seqr = Sequencer("seqr", self)
        self.cdb_set("SEQR", self.seqr)
        self.agent = Agent("agent", self)
        self.scoreboard = Scoreboard("scoreboard", self)
        self.coverage = Coverage("coverage", self)

    def connect_phase(self):
        self.agent.seq_item_port.connect(self.seqr.seq_item_export)
        self.agent.cmd_port.connect(self.scoreboard.cmd_export)
        self.agent.tlm_port.connect(self.scoreboard.tlm_export)
        self.agent.cmd_port.connect(self.coverage.cmd_export)


class Agent(uvm_agent):
    def build_phase(self):
        self.cdb_set("dut", cocotb.top)
        self.cdb_set("bfm", FunctionalModel(self.cdb_get("dut")))
        self.monitor = Monitor("monitor", self)
        self.cmd_port = self.monitor.cmd_port
        self.tlm_port = self.monitor.tlm_port
        if self.active():
            self.driver = Driver("driver", self)
            self.seq_item_port = self.driver.seq_item_port
```

When this runs, this is the traceback:

```
# Traceback (most recent call last):
#
# File "C:\work\RioxI2cCtrl\tb\cocotb\.conda\lib\site-packages\pyuvm\extension_classes.py", line 41, in test
#
#   await uvm_root().run_test(cls)
#
# File "C:\work\RioxI2cCtrl\tb\cocotb\.conda\lib\site-packages\pyuvm\s13_uvm_component.py", line 417, in run_test
#
#   self.running_phase.traverse(self.uvm_test_top)
#
# File "C:\work\RioxI2cCtrl\tb\cocotb\.conda\lib\site-packages\pyuvm\s09_phasing.py", line 65, in traverse
#
#   cls.traverse(child)
#
# File "C:\work\RioxI2cCtrl\tb\cocotb\.conda\lib\site-packages\pyuvm\s09_phasing.py", line 65, in traverse
#
#   cls.traverse(child)
#
# File "C:\work\RioxI2cCtrl\tb\cocotb\.conda\lib\site-packages\pyuvm\s09_phasing.py", line 63, in traverse
#
#   cls.execute(comp)  # first we execute this node then its children
#
# File "C:\work\RioxI2cCtrl\tb\cocotb\.conda\lib\site-packages\pyuvm\s09_phasing.py", line 45, in execute
#
#   method()
#
# File "C:\work\RioxI2cCtrl\tb\cocotb\new_riox_i2c_ctrl.py", line 65, in build_phase
#
#   if self.get_is_active() == pyuvm.uvm_active_passive_enum.UVM_ACTIVE:
#
# File "C:\work\RioxI2cCtrl\tb\cocotb\.conda\lib\site-packages\pyuvm\s13_predefined_component_classes.py", line 74, in get_is_active
#
#   return self.is_active
#
# AttributeError: 'Agent' object has no attribute 'is_active'. Did you mean: 'active'?
```

In my agent, I tried using self.active() as well as self.get_is_active() == ... with the same results. It seems like uvm_agent.__init__() is not getting called by the time I reach this.

In systemverilog, the driver instantiation is determined in the build phase, which I believe I am following correctly.

**Comment by tj-scherer** [comment]
Ah I spoke too soon, I forgot to use super().build_phase()
