### ISSUE TITLE
Accessing pyuvm/cocotb from custom build infra

### ISSUE THREAD

**Issue by sbhutada** [pyuvm/pyuvm#190]
I am trying to integrate pyuvm/cocotb inside larger build infrastructure. What is the best way to do this? I thought venv might work. Any suggestions? Thanks.
Installation steps:
```
cd $COMMON_ROOT/scripts/rtlutils
python -m venv uvmpy/venv
/usr/local/fbcode/platform010/bin/python3.8 -m venv uvmpy/venv
cd uvmpy/
source venv/bin/activate
git clone https://github.com/pyuvm/pyuvm
cd pyuvm
python -m pip install .
```

User usage steps:
```
setenv UVMPY $COMMON_ROOT/scripts/rtlutils/uvmpy
source $UVMPY/venv/bin/activate.csh
cp -rf $UVMPY/pyuvm/examples .
cd examples/TinyALU/
```
Update Makefile to add this to it:
include ${COMMON_ROOT}/scripts/rtlutils/pyuvm/cleanall.mk
```
make sim
Traceback (most recent call last):
  File ".../uvmpy/venv/bin/cocotb-config", line 5, in <module>
    from cocotb.config import main
  File ".../uvmpy/venv/lib/python3.8/site-packages/cocotb/__init__.py", line 43, in <module>
    import cocotb.handle
  File ".../uvmpy/venv/lib/python3.8/site-packages/cocotb/handle.py", line 39, in <module>
    from cocotb import simulator
ImportError: cannot import name 'simulator' from partially initialized module 'cocotb' (most likely due to a circular import) (.../uvmpy/venv/lib/python3.8/site-packages/cocotb/__init__.py)
Makefile:26: /Makefile.sim: No such file or directory
make: *** No rule to make target '/Makefile.sim'.  Stop.
```
Is there a way to use Makefiles without coco-tb-config?

**Comment by sbhutada** [comment]
I used 3.12 and it seems to work.

I just need to know how to avoid using cocotb-config - or how to integrate this in larger build infrastructure.

Thanks.

**Comment by raysalemi** [comment]
I'm not certain of the answer to your question as it relates to cocotb.  

I use venv myself when I am developing or using pyuvm.

**Comment by raysalemi** [comment]
The cocotb issues section is a better place to ask this question.

**Comment by sbhutada** [comment]
Thanks
